# https://docs.microsoft.com/azure/devops/pipelines/ecosystems/xamarin
pool:
  vmImage: 'macOS-10.15' # For Windows, use 'windows-2019'; For Mac use 'macOS-10.15'

trigger:
  - master
  - OKTA-*
  - test-*
  - *-rc
  - release-*

steps:
- checkout: self
  persistCredentials: true
- task: NuGetToolInstaller@0

- task: Bash@3
  name: CakeBuild
  inputs:
    targetType: 'filePath'
    filePath: './build-from-azure.sh'
  env:
    BUILD_ENVIRONMENT: "AZURE"
    GITHUB_USERNAME: $(GITHUB_USERNAME)
    GITHUB_ACCESS_TOKEN: $(GITHUB_ACCESS_TOKEN)
    OKTA_CLIENT_ID: $(OKTA_CLIENT_ID)
    OKTA_DOMAIN: $(OKTA_DOMAIN)
